### ISSUE TITLE
minor improvements - suggestions

### ISSUE THREAD

**Issue by aaronkaplan** [certat/intelmq-webinput-csv#33]
- [ ] (high prio) : allow for other delimiter characters than [';', '#', ',']: spaces are valid as well, TAB characters etc... basically a user should be able to specify the delimiter freely. 
- [x] if you upload a file and want to skip 129 lines , the default behaviour is to load only 100 lines. But this does not mean that 100 lines - //after// skipping the 129 lines are loaded! This is confusing and should be fixed.
- [ ] text in the second screen should not be a HTML INPUT field but a HTML TEXTAREA field.

**Comment by wagner-certat** [comment]
>  text in the second screen should not be a HTML INPUT field but a HTML TEXTAREA field.

You mean the text selector? So it's not referring to an existing boilerplate text but a new - temporary - one?
We (3) need to discuss the whole text topic first IMHO.

**Comment by wagner-certat** [comment]
> basically a user should be able to specify the delimiter freely.

So a text field?

**Comment by wagner-certat** [comment]
>  text in the second screen should not be a HTML INPUT field but a HTML TEXTAREA field.

See also #11

**Comment by aaronkaplan** [comment]
I think yes. That makes sense. In addition a few radio boxes with the most common delimiters. 

Might need a bit of JS onclick() 

---
Mobile

**Comment by aaronkaplan** [comment]
Okay needs to be saved in the session/request. No idea yet on how to push it to the bots 

---
Mobile

**Comment by wagner-certat** [comment]
First item: was not necessary in the last years, so most probably not needed
Third item is already covered by #11

Closing here
