### ISSUE TITLE
Missing files after installed

### ISSUE THREAD

**Issue by grodriguezl** [certat/intelmq-webinput-csv#62]
Hi, 

After the package installation with git clone and pip install, files from `bin` and `static` directories are not copied to the package directory (`/usr/local/lib/python3.6/site-packages/intelmq_webinput_csv`).
I could fix it by adding all `bin` and `static` sub-directories to package_data in `setup.py` but I don't know if the installation is supposed to copy these files or I am missing something.

I'm using CentOS 7, pip 19.2.3 and Python 3.6.8

**Comment by wagner-certat** [comment]
Thanks for the report.

Interestingly, it works fine on my system (opensuse leap 15.1, pip 10.0.1 python 3.6).
I now added a manifest file to include the files explicitly and I guess I won't have time in the near future to look at this issue in detail.

**Comment by bernhardreiter** [comment]
@grodriguezl  Did you retest if the situation has improved with the 0.2.0 release?

**Comment by grodriguezl** [comment]
No, I'm not working with intelmq anymore

**Comment by bernhardreiter** [comment]
@grodriguezl thanks for letting us know. (Of course I'm curious, why you do not use it anymore, but feel free to only answer if you feel like it.)

@wagner-certat I suggest to close this issue.

**Comment by grodriguezl** [comment]
I switched jobs.
Good luck with intelmq project!!

**Comment by bernhardreiter** [comment]
@grodriguezl thanks again for the feedback and all the best for your new job!
