### ISSUE TITLE
Save raw data in event

### ISSUE THREAD

**Issue by ghost** [certat/intelmq-webinput-csv#66]

**Comment by wagner-certat** [comment]
For this we also need to keep track of CSV comments and headers. Maybe use IntelMQ's RewindableFileHandle?

**Comment by rkokkelk** [comment]
Is this not already resolved by implementation: https://github.com/certat/intelmq-webinput-csv/blob/51b4cb92cd958ba8a6bd174fdc705ce155cb5712/intelmq_webinput_csv/bin/backend.py#L460

**Comment by sebix** [comment]
Yes, I fixed that in https://github.com/certat/intelmq-webinput-csv/commit/911a0855af7cd566f23bfdd2a62f42040361e641 but forgot to close this issue.
