### ISSUE TITLE
destination_pipeline_queue is outside intelmq in config file

### ISSUE THREAD

**Issue by grodriguezl** [certat/intelmq-webinput-csv#70]
After the last changes, `destination_pipeline_queue` is read from outside `intelmq` from config file.

Now:
https://github.com/certat/intelmq-webinput-csv/blob/fc42a6eaa2bc96d7eafb4efb1f3afede316675d7/intelmq_webinput_csv/bin/backend.py#L392

Before:
https://github.com/certat/intelmq-webinput-csv/blob/7cc1a2bb70febcaf53d9c0e2c5305c525cd41335/intelmq_webinput_csv/bin/backend.py#L382

In user guide it is not clear if `destination_pipeline_*` should be placed inside `intelmq` as it was before these changes or not.

**Comment by wagner-certat** [comment]
Thanks for the reminder and sorry for the breaking change. I added docs and reasoning (in NEWS) now.
