### ISSUE TITLE
TypeError on submit when using IntelMQ v3

### ISSUE THREAD

**Issue by fwesters** [certat/intelmq-webinput-csv#76]
# Problem 
When using webinput-csv together with IntelMQ version 3, the following error is thrown when submitting the data to IntelMQ. 
```
TypeError: create() got multiple values for argument 'logger', referer: <webinput_url>/preview
```
# Analysis
The traceback of the exception leads to the function ```submit()``` in ```backend.py```. On line 395-397, we find:
```
     destination_pipeline = PipelineFactory.create(PipelineParameters(),
                                                  logger=app.logger,
                                                  direction='destination')
```
The first argument is the object ```PipelineParameters()```. This was correct for intelMQ version 2, but in IntelMQ 3, the function call has been changed from
```
    def create(parameters: object, logger: object,
               direction: Optional[str] = None,
               queues: Optional[Union[str, list, dict]] = None,
               bot=None):
```
to the following:
```
    def create(logger, broker=None, direction=None, queues=None, pipeline_args=None, load_balance=False, is_multithreaded=False):
```
Hence, the ```PipelineParameters()``` object is passed as ```logger``` into the ```create``` function.

# Solution
In IntelMQ v3, the ```parameters```  parameter has been renamed to ```pipeline_args```. Therefore we can fix the error by replacing line 395-397 by
```
    pipeline_parameters = PipelineParameters().__dict__
    destination_pipeline = PipelineFactory.create(pipeline_args=pipeline_parameters,
                                                  logger=app.logger,
                                                  direction='destination')

```
Can this be added to a new (IntelMQ3 compatible) version of webinput-csv?

**Comment by wagner-certat** [comment]
Thanks for the report, the Webinput indeed needs to be adapted.

@Intevation is rewriting the backend in the next weeks, funded by CERT-BUND. I think it's not worth the effort to invest time into it before the rewrite is completed.

**Comment by sebix** [comment]
[Intevation/intelmq-webinput-csv](https://github.com/Intevation/intelmq-webinput-csv/) also only addresses IntelMQ < 3 IIRC but the code doesn't use the parameter name for passing the pipeline parameters:
https://github.com/Intevation/intelmq-webinput-csv/blob/c07e203d15a7b4a60bb9928b010c76f4096b3100/intelmq_webinput_csv/serve.py#L114
You could try their fork

**Comment by aaronkaplan** [comment]
(sorry if this is a stupid question, have to admit, I did not check): is there an automatic unit test for potential CSVs which get HTTP POSTed/submitted to webinput-csv? 

My experience with it is, that;s quite flaky in interpreting CSVs...

**Comment by sebix** [comment]
> (sorry if this is a stupid question, have to admit, I did not check): is there an automatic unit test for potential CSVs which get HTTP POSTed/submitted to webinput-csv?

No, the webinput-csv does not have any automated tests.

**Comment by sebix** [comment]
> https://github.com/Intevation/intelmq-webinput-csv/ is now compatible with IntelMQ 3.0 (since commit [ff0c02b](https://github.com/certat/intelmq-webinput-csv/commit/ff0c02bd90c1384bbcaffafce53351201be75095))

the version on PyPI is compatible with IntelMQ 3.0 as well: https://pypi.org/project/intelmq-webinput-csv/
